# Generated by Django 2.1 on 2019-03-30 17:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanycharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.IntegerField(max_length=255, verbose_name='price')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('description', models.TextField(verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'campany charge',
                'verbose_name_plural': 'campany charges',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('address', models.CharField(max_length=555, verbose_name='address')),
                ('city', models.CharField(max_length=555, verbose_name='city')),
                ('state', models.CharField(max_length=555, verbose_name='city')),
                ('phone', models.CharField(max_length=255, verbose_name='phone')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(max_length=255, verbose_name='image1')),
                ('image2', models.CharField(max_length=255, verbose_name='image2')),
                ('image3', models.CharField(max_length=255, verbose_name='image3')),
                ('image4', models.CharField(max_length=255, verbose_name='image4')),
            ],
            options={
                'verbose_name': 'images',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('price', models.FloatField(max_length=255, verbose_name='price')),
                ('quantity', models.IntegerField(max_length=255, verbose_name='quantity')),
                ('total', models.FloatField(max_length=255, verbose_name='total')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardviews.Customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('price', models.FloatField(max_length=255, verbose_name='price')),
                ('cpu', models.CharField(max_length=455, verbose_name='cpu')),
                ('category', models.CharField(max_length=255, verbose_name='category')),
                ('brand', models.CharField(max_length=255, verbose_name='brand')),
                ('camera', models.CharField(max_length=255, verbose_name='camera')),
                ('size', models.CharField(max_length=255, verbose_name='size')),
                ('weight', models.CharField(max_length=470, verbose_name='weight')),
                ('display', models.CharField(max_length=470, verbose_name='display')),
                ('battery', models.CharField(max_length=470, verbose_name='battery')),
                ('memory', models.CharField(max_length=255, verbose_name='memory')),
                ('description', models.TextField(verbose_name='description')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardviews.Images', verbose_name='images')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Productcharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=255, verbose_name='quantity')),
                ('price', models.IntegerField(max_length=255, verbose_name='price')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('description', models.TextField(verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardviews.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product charges',
                'verbose_name_plural': 'product charges',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardviews.Product', verbose_name='product'),
        ),
    ]
